#!/bin/bash
# This hook is sourced after every virtualenv is activated.

if [ ! -z "$ZSH_VERSION" ]; then
    PS1="$_OLD_VIRTUAL_PS1"
    _OLD_RPROMPT="$PROMPT"
    PROMPT="$PROMPT(`basename \"$VIRTUAL_ENV\"`) "
fi
